//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymindsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Members
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public int group_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> time_ar { get; set; }
        public Nullable<System.DateTime> time_offer { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Group Group { get; set; }
    }
}
